[package]
name = "whistle_cli"
version = "0.1.0"
authors = ["Filippo Rossi"]
edition = "2018"

[[bin]]
name = "whistle"
path = "src/main.rs"

[dependencies]
whistle_lexer = { path = "../lexer/" }
whistle_parser = { path = "../parser/" }
clap = "2.33.3"
