[package]
name = "whistle_core"
version = "0.1.0"
authors = ["Filippo Rossi"]
edition = "2018"

[dependencies]
whistle_atoms = { path = "../atoms/" }
serde = { version = "1.0", features = ["derive"] }
nom = "5"
nom_locate = "2.0.0"
enum_kind = "0.2.0" # we could and should probably self host this
